In [1]:
from randomuser import RandomUser
import pandas as pd

In [2]:
r = RandomUser()

In [3]:
some_list = r.generate_users(10)

In [4]:
some_list

[<randomuser.RandomUser at 0x23d1949a1a0>,
 <randomuser.RandomUser at 0x23d19499f30>,
 <randomuser.RandomUser at 0x23d19499f90>,
 <randomuser.RandomUser at 0x23d19499f60>,
 <randomuser.RandomUser at 0x23d1949a110>,
 <randomuser.RandomUser at 0x23d19499fc0>,
 <randomuser.RandomUser at 0x23d1949a140>,
 <randomuser.RandomUser at 0x23d19499f00>,
 <randomuser.RandomUser at 0x23d1949a050>,
 <randomuser.RandomUser at 0x23d1949a230>]

In [5]:
name = r.get_full_name()

In [6]:
name

'Imar Van der Ven'

In [10]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Veronica Schwaiger   veronica.schwaiger@example.com
Rodi Van den Houten   rodi.vandenhouten@example.com
آوین سلطانی نژاد   awyn.sltnynjd@example.com
Sander Sørensen   sander.sorensen@example.com
Murat Akman   murat.akman@example.com
Bernard Meunier   bernard.meunier@example.com
Ruben Santiago   ruben.santiago@example.com
Louanne Olivier   louanne.olivier@example.com
Beatrice Leroux   beatrice.leroux@example.com
Inara Viana   inara.viana@example.com

In [11]:
# Generatte picture of random users
for user in some_list:
    print (user.get_picture())

https://randomuser.me/api/portraits/women/37.jpg
https://randomuser.me/api/portraits/men/33.jpg
https://randomuser.me/api/portraits/women/42.jpg
https://randomuser.me/api/portraits/men/88.jpg
https://randomuser.me/api/portraits/men/13.jpg
https://randomuser.me/api/portraits/men/25.jpg
https://randomuser.me/api/portraits/men/27.jpg
https://randomuser.me/api/portraits/women/12.jpg
https://randomuser.me/api/portraits/women/3.jpg
https://randomuser.me/api/portraits/women/36.jpg

In [14]:
 #To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.
 
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [15]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Adele Gonzalez,female,Ekeberg,Telemark,adele.gonzalez@example.com,1998-03-06T01:30:27.477Z,https://randomuser.me/api/portraits/women/96.jpg
1,Stephen Fletcher,male,Liverpool,West Glamorgan,stephen.fletcher@example.com,1989-07-04T11:52:32.361Z,https://randomuser.me/api/portraits/men/70.jpg
2,Amanda Maunu,female,Karkkila,North Karelia,amanda.maunu@example.com,1959-09-27T16:33:39.517Z,https://randomuser.me/api/portraits/women/70.jpg
3,Leevi Toro,male,Ristiina,South Karelia,leevi.toro@example.com,1979-02-28T13:04:50.446Z,https://randomuser.me/api/portraits/men/37.jpg
4,Helena Dietz,female,Nederland,Zuid-Holland,helena.dietz@example.com,1945-10-18T10:31:28.032Z,https://randomuser.me/api/portraits/women/96.jpg
5,Soledad Duran,female,Zaragoza,Andalucía,soledad.duran@example.com,1965-08-10T06:25:38.993Z,https://randomuser.me/api/portraits/women/96.jpg
6,Oscar Hicks,male,Celbridge,Tipperary,oscar.hicks@example.com,1979-01-02T07:04:33.408Z,https://randomuser.me/api/portraits/men/15.jpg
7,Paula Robertson,female,Chesapeake,Vermont,paula.robertson@example.com,1962-06-22T13:57:10.001Z,https://randomuser.me/api/portraits/women/19.jpg
8,Jennifer Lowe,female,Gorey,Laois,jennifer.lowe@example.com,1946-01-06T14:33:07.106Z,https://randomuser.me/api/portraits/women/23.jpg
9,Thomas Vincent,male,Montpellier,Val-D'Oise,thomas.vincent@example.com,1994-06-23T18:47:25.104Z,https://randomuser.me/api/portraits/men/59.jpg

In [16]:
df1 = pd.DataFrame(get_users())

In [20]:
df1

,Name,Gender,City,State,Email,DOB,Picture
0,Svetlana Großmann,female,Wegberg,Niedersachsen,svetlana.grossmann@example.com,1977-07-15T06:45:24.265Z,https://randomuser.me/api/portraits/women/88.jpg
1,Jeffrey Steward,male,Orange,Western Australia,jeffrey.steward@example.com,1983-10-25T19:14:30.374Z,https://randomuser.me/api/portraits/men/1.jpg
2,Aurora Green,female,Taupo,Waikato,aurora.green@example.com,1971-11-13T13:50:14.371Z,https://randomuser.me/api/portraits/women/24.jpg
3,Harold Young,male,Arlington,New Jersey,harold.young@example.com,1955-05-23T14:39:25.412Z,https://randomuser.me/api/portraits/men/62.jpg
4,Birgit Blanchard,female,Savièse,Valais,birgit.blanchard@example.com,1964-05-07T04:23:56.895Z,https://randomuser.me/api/portraits/women/56.jpg
5,Rachel David,female,Nîmes,Calvados,rachel.david@example.com,1985-06-08T19:45:18.259Z,https://randomuser.me/api/portraits/women/17.jpg
6,Christopher Meyer,male,Londonderry,Warwickshire,christopher.meyer@example.com,1991-03-07T03:13:36.417Z,https://randomuser.me/api/portraits/men/98.jpg
7,Yolande Roy,female,Apples,Nidwalden,yolande.roy@example.com,1971-06-28T07:53:36.656Z,https://randomuser.me/api/portraits/women/93.jpg
8,Sarita Van den Dries,female,Buren,Utrecht,sarita.vandendries@example.com,1956-05-21T06:23:34.640Z,https://randomuser.me/api/portraits/women/72.jpg
9,Cécile Le Gall,female,Leibstadt,Jura,cecile.legall@example.com,1979-03-28T17:33:06.461Z,https://randomuser.me/api/portraits/women/28.jpg

In [22]:
# Fruitvice API

import requests
import json

In [23]:
data = requests.get("https://www.fruityvice.com/api/fruit/all")

In [24]:
results = json.loads(data.text)

In [25]:
pd.DataFrame(results)

,genus,name,id,family,order,nutritions
0,Malus,Apple,6,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.3, 'fat':..."
1,Prunus,Apricot,35,Rosaceae,Rosales,"{'carbohydrates': 3.9, 'protein': 0.5, 'fat': ..."
2,Persea,Avocado,84,Lauraceae,Laurales,"{'carbohydrates': 8.53, 'protein': 2, 'fat': 1..."
3,Musa,Banana,1,Musaceae,Zingiberales,"{'carbohydrates': 22, 'protein': 1, 'fat': 0.2..."
4,Rubus,Blackberry,64,Rosaceae,Rosales,"{'carbohydrates': 9, 'protein': 1.3, 'fat': 0...."
5,Fragaria,Blueberry,33,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0, 'fat': 0...."
6,Prunus,Cherry,9,Rosaceae,None,"{'carbohydrates': 12, 'protein': 1, 'fat': 0.3..."
7,Selenicereus,Dragonfruit,80,Cactaceae,Caryophyllales,"{'carbohydrates': 9, 'protein': 9, 'fat': 1.5,..."
8,Durio,Durian,60,Malvaceae,Malvales,"{'carbohydrates': 27.1, 'protein': 1.5, 'fat':..."
9,Sellowiana,Feijoa,76,Myrtaceae,Myrtoideae,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."
10,Ficus,Fig,68,Moraceae,Rosales,"{'carbohydrates': 19, 'protein': 0.8, 'fat': 0..."
11,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,"{'carbohydrates': 10, 'protein': 0.9, 'fat': 0..."
12,Vitis,Grape,81,Vitaceae,Vitales,"{'carbohydrates': 18.1, 'protein': 0.72, 'fat'..."
13,Vitis,Grapes,47,Vitaceae,Vitales,"{'carbohydrates': 18.1, 'protein': 0.72, 'fat'..."
14,Malus,GreenApple,72,Rosaceae,Rosales,"{'carbohydrates': 3.1, 'protein': 0.4, 'fat': ..."
15,Psidium,Guava,37,Myrtaceae,Myrtales,"{'carbohydrates': 14, 'protein': 2.6, 'fat': 1..."
16,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,"{'carbohydrates': 15, 'protein': 1.1, 'fat': 0..."
17,Actinidia,Kiwifruit,85,Actinidiaceae,Ericales,"{'carbohydrates': 14.6, 'protein': 1.14, 'fat'..."
18,Citrus,Lemon,26,Rutaceae,Sapindales,"{'carbohydrates': 9, 'protein': 1.1, 'fat': 0...."
19,Citrus,Lime,44,Rutaceae,Sapindales,"{'carbohydrates': 8.4, 'protein': 0.3, 'fat': ..."
20,Vaccinium,Lingonberry,65,Ericaceae,Ericales,"{'carbohydrates': 11.3, 'protein': 0.75, 'fat'..."
21,Litchi,Lychee,67,Sapindaceae,Sapindales,"{'carbohydrates': 17, 'protein': 0.8, 'fat': 0..."
22,Mangifera,Mango,27,Anacardiaceae,Sapindales,"{'carbohydrates': 15, 'protein': 0.82, 'fat': ..."
23,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,"{'carbohydrates': 8, 'protein': 0, 'fat': 0, '..."
24,Morus,Morus,82,Moraceae,Rosales,"{'carbohydrates': 9.8, 'protein': 1.44, 'fat':..."
25,Citrus,Orange,2,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 1, 'fat': 0...."
26,Carica,Papaya,42,Caricaceae,Caricacea,"{'carbohydrates': 11, 'protein': 0, 'fat': 0.4..."
27,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,"{'carbohydrates': 22.4, 'protein': 2.2, 'fat':..."
28,Pyrus,Pear,4,Rosaceae,Rosales,"{'carbohydrates': 15, 'protein': 0.4, 'fat': 0..."
29,Diospyros,Persimmon,52,Ebenaceae,Rosales,"{'carbohydrates': 18, 'protein': 0, 'fat': 0, ..."
30,Ananas,Pineapple,10,Bromeliaceae,Poales,"{'carbohydrates': 13.12, 'protein': 0.54, 'fat..."
31,Cactaceae,Pitahaya,78,Cactaceae,Caryophyllales,"{'carbohydrates': 7, 'protein': 1, 'fat': 0.4,..."
32,Prunus,Plum,71,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.7, 'fat':..."
33,Punica,Pomegranate,79,Lythraceae,Myrtales,"{'carbohydrates': 18.7, 'protein': 1.7, 'fat':..."
34,Rubus,Raspberry,23,Rosaceae,Rosales,"{'carbohydrates': 12, 'protein': 1.2, 'fat': 0..."
35,Fragaria,Strawberry,3,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0.8, 'fat': ..."
36,Citrus,Tangerine,77,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 0, 'fat': 0...."
37,Solanum,Tomato,5,Solanaceae,Solanales,"{'carbohydrates': 3.9, 'protein': 0.9, 'fat': ..."
38,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."

In [26]:
df2 = pd.json_normalize(results)
df2

,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Malus,Apple,6,Rosaceae,Rosales,11.40,0.30,0.40,52,10.30
1,Prunus,Apricot,35,Rosaceae,Rosales,3.90,0.50,0.10,15,3.20
2,Persea,Avocado,84,Lauraceae,Laurales,8.53,2.00,14.66,160,0.66
3,Musa,Banana,1,Musaceae,Zingiberales,22.00,1.00,0.20,96,17.20
4,Rubus,Blackberry,64,Rosaceae,Rosales,9.00,1.30,0.40,40,4.50
5,Fragaria,Blueberry,33,Rosaceae,Rosales,5.50,0.00,0.40,29,5.40
6,Prunus,Cherry,9,Rosaceae,None,12.00,1.00,0.30,50,8.00
7,Selenicereus,Dragonfruit,80,Cactaceae,Caryophyllales,9.00,9.00,1.50,60,8.00
8,Durio,Durian,60,Malvaceae,Malvales,27.10,1.50,5.30,147,6.75
9,Sellowiana,Feijoa,76,Myrtaceae,Myrtoideae,8.00,0.60,0.40,44,3.00
10,Ficus,Fig,68,Moraceae,Rosales,19.00,0.80,0.30,74,16.00
11,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,10.00,0.90,0.60,44,0.00
12,Vitis,Grape,81,Vitaceae,Vitales,18.10,0.72,0.16,69,16.00
13,Vitis,Grapes,47,Vitaceae,Vitales,18.10,0.72,0.16,69,15.48
14,Malus,GreenApple,72,Rosaceae,Rosales,3.10,0.40,0.10,21,6.40
15,Psidium,Guava,37,Myrtaceae,Myrtales,14.00,2.60,1.00,68,9.00
16,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,15.00,1.10,0.50,61,9.00
17,Actinidia,Kiwifruit,85,Actinidiaceae,Ericales,14.60,1.14,0.50,61,8.90
18,Citrus,Lemon,26,Rutaceae,Sapindales,9.00,1.10,0.30,29,2.50
19,Citrus,Lime,44,Rutaceae,Sapindales,8.40,0.30,0.10,25,1.70
20,Vaccinium,Lingonberry,65,Ericaceae,Ericales,11.30,0.75,0.34,50,5.74
21,Litchi,Lychee,67,Sapindaceae,Sapindales,17.00,0.80,0.44,66,15.00
22,Mangifera,Mango,27,Anacardiaceae,Sapindales,15.00,0.82,0.38,60,13.70
23,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,8.00,0.00,0.00,34,8.00
24,Morus,Morus,82,Moraceae,Rosales,9.80,1.44,0.39,43,8.10
25,Citrus,Orange,2,Rutaceae,Sapindales,8.30,1.00,0.20,43,8.20
26,Carica,Papaya,42,Caricaceae,Caricacea,11.00,0.00,0.40,43,1.00
27,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,22.40,2.20,0.70,97,11.20
28,Pyrus,Pear,4,Rosaceae,Rosales,15.00,0.40,0.10,57,10.00
29,Diospyros,Persimmon,52,Ebenaceae,Rosales,18.00,0.00,0.00,81,18.00
30,Ananas,Pineapple,10,Bromeliaceae,Poales,13.12,0.54,0.12,50,9.85
31,Cactaceae,Pitahaya,78,Cactaceae,Caryophyllales,7.00,1.00,0.40,36,3.00
32,Prunus,Plum,71,Rosaceae,Rosales,11.40,0.70,0.28,46,9.92
33,Punica,Pomegranate,79,Lythraceae,Myrtales,18.70,1.70,1.20,83,13.70
34,Rubus,Raspberry,23,Rosaceae,Rosales,12.00,1.20,0.70,53,4.40
35,Fragaria,Strawberry,3,Rosaceae,Rosales,5.50,0.80,0.40,29,5.40
36,Citrus,Tangerine,77,Rutaceae,Sapindales,8.30,0.00,0.40,45,9.10
37,Solanum,Tomato,5,Solanaceae,Solanales,3.90,0.90,0.20,74,2.60
38,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,8.00,0.60,0.20,30,6.00

In [27]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')